apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    role: vote
spec:
  selector:
    role: vote
  ports:
    - port: 8080 ## For Cluster and For ExternalIP
      targetPort: 80 ## For Pod
      nodePort: 30000 ## For outside world
  type: NodePort
  externalIPs:
    - 192.168.56.103
