apiVersion: v1
kind: Service
metadata:
  name: bar-app
spec:
  selector:
    app: bar-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30036 # specified explictly
      protocol: TCP
