apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-green
  namespace: instavote
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # no of extra pod to be created while deploying
      maxUnavailable: 1 # no of pod to be unavailable wile deploying
  revisionHistoryLimit: 4
  paused: false
  minReadySeconds: 10
  selector:
    matchLabels:
      role: vote
    matchExpressions:
      - {key: version, operator: In, values: [v1, v2, v3, v4, v5]}
  template:
    metadata:
      name: vote
      labels:
        app: python
        role: vote
        version: v4
        release: bluegreen
        code: green
    spec:
      containers:
        - name: app
          image: schoolofdevops/vote:v4
          ports:
            - containerPort: 80
              protocol: TCP
          # envFrom:
          #   - configMapRef:
          #       name: vote
